const wordList =[
    
        { palavra: "sol", dica: "brilha no céu e traz calor" },
        { palavra: "lua", dica: "ilumina a noite com fases diferentes" },
        { palavra: "estrela", dica: "pequenos pontos brilhantes no céu" },
        { palavra: "agua", dica: "essencial para a vida, está nos rios" },
        { palavra: "fogo", dica: "queima e traz calor" },
        { palavra: "terra", dica: "solo onde as plantas crescem" },
        { palavra: "ar", dica: "invisível, mas você respira" },
        { palavra: "montanha", dica: "muito alta, difícil de escalar" },
        { palavra: "mar", dica: "enorme e cheio de ondas" },
        { palavra: "flor", dica: "tem pétalas coloridas e perfume" },
        { palavra: "arvore", dica: "alta e com folhas verdes" },
        { palavra: "cachorro", dica: "o melhor amigo do homem" },
        { palavra: "gato", dica: "miado suave, adora carinho" },
        { palavra: "elefante", dica: "grande e com tromba longa" },
        { palavra: "leao", dica: "o rei da selva" },
        { palavra: "passaro", dica: "tem asas e canta no céu" },
        { palavra: "peixe", dica: "vive na água e nada bem" },
        { palavra: "borboleta", dica: "colorida e voa entre as flores" },
        { palavra: "abelha", dica: "faz mel e gosta de flores" },
        { palavra: "carro", dica: "tem rodas e leva você a lugares" },
        { palavra: "aviao", dica: "voa alto com passageiros" },
        { palavra: "bicicleta", dica: "duas rodas e sem motor" },
        { palavra: "trem", dica: "anda nos trilhos" },
        { palavra: "onibus", dica: "transporte público grande" },
        { palavra: "casa", dica: "onde você mora" },
        { palavra: "escola", dica: "lugar para aprender" },
        { palavra: "livro", dica: "repleto de páginas e histórias" },
        { palavra: "computador", dica: "máquina para acessar a internet" },
        { palavra: "telefone", dica: "chamadas e mensagens rápidas" },
        { palavra: "relogio", dica: "mostra o tempo" },
        { palavra: "cadeira", dica: "para sentar e descansar" },
        { palavra: "mesa", dica: "para refeições ou trabalho" },
        { palavra: "caneta", dica: "usa tinta para escrever" },
        { palavra: "lapis", dica: "escreve e pode ser apagado" },
        { palavra: "bola", dica: "usada em vários esportes" },
        { palavra: "gol", dica: "meta no futebol" },
        { palavra: "chave", dica: "abre portas e cadeados" },
        { palavra: "porta", dica: "entrada para uma sala" },
        { palavra: "janela", dica: "para olhar e deixar o ar entrar" },
        { palavra: "espelho", dica: "reflete sua imagem" },
        { palavra: "radio", dica: "toca músicas e notícias" },
        { palavra: "televisao", dica: "mostra programas e filmes" },
        { palavra: "camera", dica: "captura fotos e vídeos" },
        { palavra: "sapato", dica: "protege seus pés" },
        { palavra: "camisa", dica: "roupa para a parte superior do corpo" },
        { palavra: "chuva", dica: "cai do céu, molha tudo" },
        { palavra: "vento", dica: "invisível, mas você sente" },
        { palavra: "microfone", dica: "dá voz a muitos artistas" },
        { palavra: "estadio", dica: "onde acontecem grandes jogos" },
        { palavra: "cinema", dica: "lugar para assistir filmes" }
      
      
]