const wordList =[
    
        { palavra: "sol", dica: "brilha no céu e traz calor" },
        { palavra: "lua", dica: "ilumina a noite com fases diferentes" },
        { palavra: "estrela", dica: "pequenos pontos brilhantes no céu" },
        { palavra: "agua", dica: "essencial para a vida, está nos rios" },
        { palavra: "fogo", dica: "queima e traz calor" },
        { palavra: "terra", dica: "solo onde as plantas crescem" },
        { palavra: "ar", dica: "invisível, mas você respira" },
        { palavra: "montanha", dica: "muito alta, difícil de escalar" },
        { palavra: "mar", dica: "enorme e cheio de ondas" },
        { palavra: "flor", dica: "tem pétalas coloridas e perfume" },
        { palavra: "arvore", dica: "alta e com folhas verdes" },
        { palavra: "cachorro", dica: "o melhor amigo do homem" },
        { palavra: "gato", dica: "miado suave, adora carinho" },
        { palavra: "elefante", dica: "grande e com tromba longa" },
        { palavra: "leao", dica: "o rei da selva" },
        { palavra: "passaro", dica: "tem asas e canta no céu" },
        { palavra: "peixe", dica: "vive na água e nada bem" },
        { palavra: "borboleta", dica: "colorida e voa entre as flores" },
        { palavra: "abelha", dica: "faz mel e gosta de flores" },
        { palavra: "carro", dica: "tem rodas e leva você a lugares" },
        { palavra: "aviao", dica: "voa alto com passageiros" },
        { palavra: "bicicleta", dica: "duas rodas e sem motor" },
        { palavra: "trem", dica: "anda nos trilhos" },
        { palavra: "onibus", dica: "transporte público grande" },
        { palavra: "casa", dica: "onde você mora" },
        { palavra: "escola", dica: "lugar para aprender" },
        { palavra: "livro", dica: "repleto de páginas e histórias" },
        { palavra: "computador", dica: "máquina para acessar a internet" },
        { palavra: "telefone", dica: "chamadas e mensagens rápidas" },
        { palavra: "relogio", dica: "mostra o tempo" },
        { palavra: "cadeira", dica: "para sentar e descansar" },
        { palavra: "mesa", dica: "para refeições ou trabalho" },
        { palavra: "caneta", dica: "usa tinta para escrever" },
        { palavra: "lapis", dica: "escreve e pode ser apagado" },
        { palavra: "bola", dica: "usada em vários esportes" },
        { palavra: "gol", dica: "meta no futebol" },
        { palavra: "chave", dica: "abre portas e cadeados" },
        { palavra: "porta", dica: "entrada para uma sala" },
        { palavra: "janela", dica: "para olhar e deixar o ar entrar" },
        { palavra: "espelho", dica: "reflete sua imagem" },
        { palavra: "radio", dica: "toca músicas e notícias" },
        { palavra: "televisao", dica: "mostra programas e filmes" },
        { palavra: "camera", dica: "captura fotos e vídeos" },
        { palavra: "sapato", dica: "protege seus pés" },
        { palavra: "camisa", dica: "roupa para a parte superior do corpo" },
        { palavra: "chuva", dica: "cai do céu, molha tudo" },
        { palavra: "vento", dica: "invisível, mas você sente" },
        { palavra: "microfone", dica: "dá voz a muitos artistas" },
        { palavra: "estadio", dica: "onde acontecem grandes jogos" },
        { palavra: "cinema", dica: "lugar para assistir filmes" },
        { palavra: "desenhar", dica: "Uma habilidade artistica" },
        { palavra: "brasil", dica: "O maior pais da America do Sul" },
        { palavra: "tesoura", dica: "Usada para cortar" },
        { palavra: "nike", dica: "Uma marca de roupas e calcados" },
        { palavra: "instagram", dica: "Uma rede social popular" },
        { palavra: "martelo", dica: "Ferramenta usada para bater pregos" },
        { palavra: "alemanha", dica: "Pais europeu conhecido por sua cerveja" },
        { palavra: "escovar", dica: "Acao de limpar os dentes" },
        { palavra: "bicicleta", dica: "Um veiculo de duas rodas" },
        { palavra: "minecraft", dica: "Um jogo famoso de blocos" },
        { palavra: "windows", dica: "Um sistema operacional" },
        { palavra: "camarao", dica: "Fruto do mar muito consumido" },
        { palavra: "japao", dica: "Pais asiatico conhecido por sushi" },
        { palavra: "bumerangue", dica: "Objeto que volta ao ser arremessado" },
        { palavra: "guarana", dica: "Um refrigerante brasileiro famoso" },
        { palavra: "chocolate", dica: "Doce feito de cacau" },
        { palavra: "atletismo", dica: "Modalidade esportiva olimpica" },
        { palavra: "celular", dica: "Aparelho que usamos para ligar ou mandar mensagens" },
        { palavra: "cafe", dica: "Bebida feita com graos torrados" },
        { palavra: "tiktok", dica: "App de videos curtos" },
        { palavra: "ferro", dica: "Material metalico muito resistente" },
        { palavra: "argentina", dica: "Pais vizinho ao Brasil, famoso pelo tango" },
        { palavra: "googlar", dica: "Ato de pesquisar algo na internet" },
        { palavra: "aviao", dica: "Usado para viajar pelo ceu" },
        { palavra: "mcdonalds", dica: "Rede de fast food famosa no mundo inteiro" },
        { palavra: "sorrir", dica: "Acao de mostrar alegria com o rosto" },
        { palavra: "patins", dica: "Equipamento para deslizar no chao" },
        { palavra: "franca", dica: "Pais europeu conhecido por queijos e vinhos" },
        { palavra: "relogio", dica: "Mostra as horas" },
        { palavra: "barco", dica: "Transporte usado na agua" },
        { palavra: "pizza", dica: "Comida redonda com molho e queijo" },
        { palavra: "guitarra", dica: "Instrumento musical de cordas" },
        { palavra: "tartaruga", dica: "Animal conhecido por sua lerdeza" },
        { palavra: "samsung", dica: "Marca famosa de eletronicos" },
        { palavra: "youtube", dica: "Plataforma de videos online" },
        { palavra: "piscina", dica: "Lugar para nadar" },
        { palavra: "nuvem", dica: "Forma branca no ceu feita de vapor" },
        { palavra: "amazon", dica: "Uma loja virtual gigante" },
        { palavra: "dancar", dica: "Movimento ao som de musica" },
        { palavra: "piano", dica: "Instrumento musical com teclas" },
        { palavra: "espanha", dica: "Pais europeu conhecido por touradas" },
        { palavra: "pincel", dica: "Usado para pintar" },
        { palavra: "ketchup", dica: "Condimento feito de tomate" },
        { palavra: "fotografar", dica: "Acao de tirar fotos" },
        { palavra: "holanda", dica: "Pais das tulipas e moinhos de vento" },
        { palavra: "monalisa", dica: "Pintura famosa de Da Vinci" },
        { palavra: "whatsapp", dica: "Aplicativo de mensagens" },
        { palavra: "camelo", dica: "Animal conhecido por viver no deserto" },
        { palavra: "corrida", dica: "Competicao para ver quem e mais rapido" },
        { palavra: "ouro", dica: "Metal precioso de cor amarela" },
        { palavra: "canada", dica: "Pais famoso por sua hospitalidade e xarope de bordo" },
        { palavra: "caneta", dica: "Ferramenta para escrever" },
        { palavra: "uber", dica: "App de transporte" },
        { palavra: "escalar", dica: "Subir montanhas ou arvores" },
        { palavra: "twitter", dica: "Rede social do passarinho azul" },
        { palavra: "lua", dica: "Satelite natural da Terra" },
        { palavra: "cocacola", dica: "Bebida gaseificada famosa mundialmente" },
        { palavra: "mochila", dica: "Usada para carregar materiais" },
        { palavra: "rio", dica: "Curso de agua natural" },
        { palavra: "tesla", dica: "Empresa de carros eletricos" },
        { palavra: "telegram", dica: "App alternativo ao WhatsApp" },
        { palavra: "pantufa", dica: "Calcado confortavel para usar em casa" },
        { palavra: "yoga", dica: "Pratica de meditacao e exercicios" },
        { palavra: "facebook", dica: "Rede social de Mark Zuckerberg" },
        { palavra: "piramide", dica: "Monumento famoso do Egito" },
        { palavra: "hamburguer", dica: "Sanduiche popular" },
        { palavra: "spotify", dica: "Plataforma de musica" },
        { palavra: "saltar", dica: "Ato de pular" },
        { palavra: "tigre", dica: "Animal selvagem listrado" },
        { palavra: "londres", dica: "Capital da Inglaterra" },
        { palavra: "remar", dica: "Acao de mover um barco com remos" },
      
]